steps:
  # 1. Install Dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']

  # 2. Build Next.js App
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      # Add other build-time env vars here

  # 3. Apply Prisma Migrations (requires DB connection)
  # using cloud-sql-proxy or direct connection if in VPC
  # For simplicity in this demo, accessing via public IP with secure secret
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running Migrations..."
        npx prisma migrate deploy
    secretEnv: ['DATABASE_URL']

  # 4. Deploy to Firebase Hosting (which handles Cloud Run / Functions backend)
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project', '$PROJECT_ID', '--only', 'hosting']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
    env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: 'needs-substitution'
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'needs-substitution'
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'needs-substitution'
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'needs-substitution'
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 'needs-substitution'
  _NEXT_PUBLIC_FIREBASE_APP_ID: 'needs-substitution'
